include: "rules/constants.smk"
include: "rules/common.smk"


FNAMES, CHRS = extract_fa_fnames_and_chr(INPUT_DIR)


include: "rules/stringdecomposer.smk"
include: "rules/stv.smk"


rule all:
    input:
        rules.stringdecomposer_all.input,
        rules.stv_all.input,
    default_target: True
