include: "rules/constants.smk"
include: "rules/common.smk"


FNAMES, CHRS = extract_fa_fnames_and_chr(INPUT_DIR)


include: "rules/stringdecomposer.smk"
include: "rules/stv.smk"


outputs = [rules.stringdecomposer_all.input]

if config.get("run_stv", True):
    outputs.append(rules.stv_all.input)


rule all:
    input:
        outputs,
    default_target: True
